### ISSUE TITLE
ISE (generated by waitress)

### ISSUE THREAD

**Issue by stevepiercy** [cguardia/books#1]
Steps to reproduce:
- Search for ISBN 9781482614374.
- Edit its properties by trying to add a year.

``` text
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

stack trace

``` python
2016-04-17 04:08:37,673 ERROR [waitress][waitress] Exception when serving /manage/books/9781482614374/@@properties
Traceback (most recent call last):
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid_debugtoolbar/toolbar.py", line 178, in toolbar_tween
    return handler(request)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 90, in tm_tween
    manager.commit()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/transaction/_transaction.py", line 265, in commit
    self._callBeforeCommitHooks()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/transaction/_transaction.py", line 337, in _callBeforeCommitHooks
    hook(*args, **kws)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/substanced/catalog/deferred.py", line 629, in flush
    self._process(actions, all=all)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/substanced/catalog/deferred.py", line 684, in _process
    self.execute_actions_immediately(actions)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/substanced/catalog/deferred.py", line 698, in execute_actions_immediately
    action.execute()
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/substanced/catalog/deferred.py", line 124, in execute
    self.index.reindex_doc(self.oid, resource)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/hypatia/field/__init__.py", line 185, in reindex_doc
    return self.index_doc(docid, value)
  File "/Users/stevepiercy/projects/books/lib/python3.5/site-packages/hypatia/field/__init__.py", line 134, in index_doc
    if docid in self._fwd_index.get(value, ()):
TypeError: Object has default comparison
```

**Comment by cguardia** [comment]
Apparently, default values for publisher and author prevented sending empty values. Fixed.
